###
POST http://localhost:7000/api/users HTTP/1.1
Content-Type: application/json

{
    "nombre":"camilo",
    "email":"camilo@hut.com",
    "pais":"bolivia"
}

###
GET http://localhost:3000/api/users HTTP/1.1

### 
GET http://localhost:3000/api/users/6236158efa239bf2d08a6cbd   HTTP/1.1

###
PUT  http://localhost:3000/api/users/6236158efa239bf2d08a6cbd HTTP/1.1
Content-Type: application/json

{
    "nombre":"evaa",
    "email":"eva@peron.com",
    "pais":"españa"
}
###
DELETE http://localhost:3000/api/users/6236140743b4da54e1c3b1ed HTTP/1.1
Content-Type: application/json